### 전체 조회
GET http://localhost:8080/mydog

### 개별 조회
GET http://localhost:8080/mydog/3

### 입력
POST http://localhost:8080/mydog
Content-Type: application/json

{
  "myDogCode": 0,
  "myDogDate": "2024-06-05",
  "myDogLocation": "_myDogLocation!.value.text",
  "myDogMemo": "_myDogMemo!.value.text"
}